## Self Attention


MAKING THE INPUT EMBEDDINGS

In [1]:

import bpe as bpe

prompt = "the cat sat on the mat"
ids = bpe.encode(prompt)

14853
14932


In [2]:
ids

[116,
 104,
 101,
 32,
 99,
 97,
 116,
 32,
 115,
 97,
 116,
 32,
 111,
 110,
 32,
 116,
 104,
 101,
 32,
 109,
 97,
 116]

In [3]:
len(ids)

22

In [4]:
# making vector embeddings
import torch

torch_ids = torch.tensor(ids)

vocab_size = 275
embedded_dim = 4

embedded_layer = torch.nn.Embedding(num_embeddings=vocab_size,embedding_dim=embedded_dim)
X = embedded_layer(torch_ids)


In [5]:
X.shape

torch.Size([22, 4])

In [6]:
# positional Embeddings
import numpy as np
def pos_encoding(embedding):
    pos,d = embedding.shape
    pe = torch.zeros(pos,d)
    for j in range(pos):
        for i in (range(d//2)):
            pe[j,2*i] = np.sin(j/10000**(2*i/d))
            pe[j,2*i+1] = np.cos(j/10000**(2*i/d))
    return pe


In [7]:
pe = pos_encoding(X)
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0100,  0.9999],
        [ 0.9093, -0.4161,  0.0200,  0.9998],
        [ 0.1411, -0.9900,  0.0300,  0.9996],
        [-0.7568, -0.6536,  0.0400,  0.9992],
        [-0.9589,  0.2837,  0.0500,  0.9988],
        [-0.2794,  0.9602,  0.0600,  0.9982],
        [ 0.6570,  0.7539,  0.0699,  0.9976],
        [ 0.9894, -0.1455,  0.0799,  0.9968],
        [ 0.4121, -0.9111,  0.0899,  0.9960],
        [-0.5440, -0.8391,  0.0998,  0.9950],
        [-1.0000,  0.0044,  0.1098,  0.9940],
        [-0.5366,  0.8439,  0.1197,  0.9928],
        [ 0.4202,  0.9074,  0.1296,  0.9916],
        [ 0.9906,  0.1367,  0.1395,  0.9902],
        [ 0.6503, -0.7597,  0.1494,  0.9888],
        [-0.2879, -0.9577,  0.1593,  0.9872],
        [-0.9614, -0.2752,  0.1692,  0.9856],
        [-0.7510,  0.6603,  0.1790,  0.9838],
        [ 0.1499,  0.9887,  0.1889,  0.9820],
        [ 0.9129,  0.4081,  0.1987,  0.9801],
        [ 0.8367, -0.5477,  0.2085

In [8]:
input_embeddings = X + pe

Pre LLm text conversion Done

In [9]:
input_embeddings.shape

torch.Size([22, 4])

In [10]:
# calculating key , value , query

W_k = torch.rand(4,4)
W_v = torch.rand(4,4)
W_q = torch.rand(4,4)


K = input_embeddings @ W_k
Q = input_embeddings @ W_q
V = input_embeddings @ W_v


In [12]:
value = Q@K.T/np.sqrt(4)
attention_score = torch.nn.functional.softmax(value,dim=-1)@V



In [13]:
output_embeddigs = attention_score+input_embeddings
output_embeddigs

tensor([[-2.5483, -0.9670, -2.2716, -1.4664],
        [ 0.0283,  0.4830,  2.7781,  4.2415],
        [-0.9528,  1.9753,  0.5954,  4.0804],
        [-1.7489, -3.7977, -2.4963, -1.9383],
        [-2.1675, -1.7818, -0.3236,  0.4636],
        [-1.6490, -0.8885, -0.4010,  2.0092],
        [-2.9520, -1.1241, -2.4229, -1.6363],
        [ 0.0802, -0.7633, -0.0799, -0.0199],
        [ 1.8364,  0.2607,  1.4053,  2.6950],
        [ 0.0515, -1.7595,  0.3306,  2.5656],
        [-3.7614, -3.4032, -3.1921, -2.2492],
        [-2.9374, -2.8323, -2.5000, -2.0025],
        [ 0.3716,  2.4311,  0.1761,  3.9172],
        [ 0.1379,  2.1126,  2.7037,  3.5472],
        [ 0.2581, -1.5673, -0.2961, -0.2748],
        [-2.2377, -3.0587, -2.6607, -1.9068],
        [-2.8381, -2.9051, -0.3671,  1.4729],
        [-4.1738,  0.6860, -1.8623,  1.9054],
        [-2.3757, -1.8935, -1.9398, -1.6334],
        [ 0.6181,  0.3786, -0.1318,  2.2805],
        [ 1.4894,  0.6391,  2.2971,  4.1116],
        [-1.9042, -2.7195, -2.3684

In [14]:
output_embeddigs = torch.nn.functional.rms_norm(output_embeddigs,normalized_shape=output_embeddigs.shape)
output_embeddigs


tensor([[-1.1974, -0.4544, -1.0674, -0.6890],
        [ 0.0133,  0.2270,  1.3054,  1.9930],
        [-0.4477,  0.9282,  0.2798,  1.9173],
        [-0.8218, -1.7845, -1.1730, -0.9108],
        [-1.0185, -0.8372, -0.1521,  0.2179],
        [-0.7748, -0.4175, -0.1884,  0.9441],
        [-1.3871, -0.5282, -1.1385, -0.7689],
        [ 0.0377, -0.3587, -0.0376, -0.0094],
        [ 0.8629,  0.1225,  0.6603,  1.2663],
        [ 0.0242, -0.8268,  0.1553,  1.2055],
        [-1.7674, -1.5991, -1.4999, -1.0569],
        [-1.3803, -1.3309, -1.1747, -0.9410],
        [ 0.1746,  1.1424,  0.0828,  1.8406],
        [ 0.0648,  0.9927,  1.2704,  1.6668],
        [ 0.1213, -0.7365, -0.1391, -0.1291],
        [-1.0515, -1.4372, -1.2502, -0.8960],
        [-1.3336, -1.3650, -0.1725,  0.6921],
        [-1.9612,  0.3223, -0.8751,  0.8953],
        [-1.1163, -0.8897, -0.9115, -0.7675],
        [ 0.2904,  0.1779, -0.0619,  1.0716],
        [ 0.6998,  0.3003,  1.0794,  1.9320],
        [-0.8948, -1.2778, -1.1129

In [ ]:
def feedforward():
    pass